export const APP_SEARCH_KIND = {
  COMMAND: 'command',
  PAGE: 'page',
  CALENDAR_EVENT: 'calendar_event',
  ITEM: 'item',
  COLLECTION: 'collection',
  PERSONA: 'persona',
  SAVINGS_TARGET: 'savings_target',
  PORTFOLIO_ASSET: 'portfolio_asset',
  FINANCE_ACCOUNT: 'finance_account',
}

export const APP_SEARCH_KIND_LABEL = {
  [APP_SEARCH_KIND.COMMAND]: 'Polecenia',
  [APP_SEARCH_KIND.PAGE]: 'Nawigacja',
  [APP_SEARCH_KIND.CALENDAR_EVENT]: 'Kalendarz',
  [APP_SEARCH_KIND.ITEM]: 'Itemy',
  [APP_SEARCH_KIND.COLLECTION]: 'Kolekcje',
  [APP_SEARCH_KIND.PERSONA]: 'Prims',
  [APP_SEARCH_KIND.SAVINGS_TARGET]: 'Oszczędności',
  [APP_SEARCH_KIND.PORTFOLIO_ASSET]: 'Portfel',
  [APP_SEARCH_KIND.FINANCE_ACCOUNT]: 'Konta',
}

export const APP_SEARCH_KIND_ORDER = [
  APP_SEARCH_KIND.COMMAND,
  APP_SEARCH_KIND.PAGE,
  APP_SEARCH_KIND.CALENDAR_EVENT,
  APP_SEARCH_KIND.ITEM,
  APP_SEARCH_KIND.COLLECTION,
  APP_SEARCH_KIND.PERSONA,
  APP_SEARCH_KIND.SAVINGS_TARGET,
  APP_SEARCH_KIND.PORTFOLIO_ASSET,
  APP_SEARCH_KIND.FINANCE_ACCOUNT,
]
